# Generated by Django 3.1.5 on 2021-01-23 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b7573d41-f97c-4d66-bfed-7b2120f26f86'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b7573d41-f97c-4d66-bfed-7b2120f26f86'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Feed',
                'verbose_name_plural': 'Activities Feed',
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b7573d41-f97c-4d66-bfed-7b2120f26f86'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to='feed.feed')),
            ],
            options={
                'verbose_name': 'Feed like',
                'verbose_name_plural': 'Feed likes',
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b7573d41-f97c-4d66-bfed-7b2120f26f86'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(max_length=255)),
                ('file_link', models.CharField(max_length=255)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_files', to='feed.feed')),
            ],
            options={
                'verbose_name': 'Feed file',
                'verbose_name_plural': 'Feed files',
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b7573d41-f97c-4d66-bfed-7b2120f26f86'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='feed.comment')),
            ],
            options={
                'verbose_name': 'Comment like',
                'verbose_name_plural': 'Comment likes',
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b7573d41-f97c-4d66-bfed-7b2120f26f86'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(max_length=255)),
                ('file_link', models.CharField(max_length=255)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_files', to='feed.comment')),
            ],
            options={
                'verbose_name': 'Comment file',
                'verbose_name_plural': 'Comment files',
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comment', to='feed.feed'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
